server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: admin-web
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
